import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F5F6F8",
  },
  header: {
    backgroundColor: "#2F66F5",
    paddingHorizontal: 24,
    paddingTop: 28,
    paddingBottom: 32,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
  },
  balanceLabel: {
    color: "#E5EDFF",
    fontSize: 18,
    marginBottom: 10,
  },
  balanceValue: {
    color: "#FFFFFF",
    fontSize: 34,
    fontWeight: "800",
    marginBottom: 24,
  },
  summaryRow: {
    flexDirection: "row",
    gap: 12,
  },
  summaryCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    padding: 18,
  },
  summaryTitle: {
    fontSize: 16,
    color: "#334155",
    marginBottom: 12,
  },
  summaryValue: {
    fontSize: 18,
    fontWeight: "800",
    color: "#0F172A",
  },
  incomeText: {
    color: "#6CC24A",
  },
  expenseText: {
    color: "#F25C2A",
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 20,
  },
  searchInput: {
    height: 52,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    paddingHorizontal: 16,
    fontSize: 15,
    color: "#0F172A",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    marginBottom: 18,
  },
  typeFilterSection: {
    marginBottom: 18,
  },

  typeFilterRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },

  filterButtonSection: {
    marginBottom: 18,
    alignItems: "flex-start",
  },
  filterButton: {
    minHeight: 44,
    paddingHorizontal: 16,
    borderRadius: 999,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#BFDBFE",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  filterButtonActive: {
    backgroundColor: "#2F66F5",
    borderColor: "#2F66F5",
  },
  filterButtonText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#2F66F5",
  },
  filterButtonTextActive: {
    color: "#FFFFFF",
  },
  filterCountBadge: {
    minWidth: 22,
    height: 22,
    borderRadius: 999,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  filterCountText: {
    fontSize: 12,
    fontWeight: "800",
    color: "#2F66F5",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.42)",
    justifyContent: "flex-end",
  },
  filterModal: {
    backgroundColor: "#F5F6F8",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 28,
  },
  filterModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  filterModalTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#0F172A",
  },
  filterModalCloseButton: {
    width: 40,
    height: 40,
    borderRadius: 999,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    alignItems: "center",
    justifyContent: "center",
  },
  filterField: {
    marginBottom: 18,
  },
  filterLabel: {
    fontSize: 15,
    fontWeight: "800",
    color: "#334155",
    marginBottom: 10,
  },
  pickerWrapper: {
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    overflow: "hidden",
    justifyContent: "center",
    height: 52,
  },
  picker: {
    color: "#0F172A",
  },
  manageCategoriesButton: {
    minHeight: 44,
    borderRadius: 14,
    backgroundColor: "#EFF6FF",
    borderWidth: 1,
    borderColor: "#BFDBFE",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginBottom: 18,
  },
  manageCategoriesText: {
    color: "#2F66F5",
    fontSize: 14,
    fontWeight: "800",
  },
  dateFilterRow: {
    flexDirection: "row",
    gap: 12,
  },
  dateInput: {
    flex: 1,
    height: 52,
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    paddingHorizontal: 14,
    fontSize: 15,
    color: "#0F172A",
  },
  dateFilterError: {
    color: "#DC2626",
    fontSize: 13,
    fontWeight: "600",
    marginTop: 10,
  },
  filterActions: {
    flexDirection: "row",
    gap: 12,
    marginTop: 4,
  },
  secondaryButton: {
    flex: 1,
    height: 52,
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#CBD5E1",
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryButtonText: {
    fontSize: 15,
    fontWeight: "800",
    color: "#475569",
  },
  primaryButton: {
    flex: 1,
    height: 52,
    borderRadius: 14,
    backgroundColor: "#2F66F5",
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButtonText: {
    fontSize: 15,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  sectionHeader: {
    marginBottom: 18,
    marginTop: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#0F172A",
  },
  sectionCount: {
    fontSize: 15,
    color: "#64748B",
  },
  listContent: {
    paddingBottom: 100,
  },
  emptyState: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    padding: 20,
    alignItems: "center",
  },
  emptyStateTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#0F172A",
    marginBottom: 8,
  },
  emptyStateText: {
    fontSize: 14,
    color: "#64748B",
    textAlign: "center",
    lineHeight: 20,
  },
});
