import { StyleSheet } from "react-native";

import type { ThemeColors } from "@/theme/colors";

export function createStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      backgroundColor: colors.primary,
      paddingHorizontal: 24,
      paddingTop: 28,
      paddingBottom: 32,
      borderBottomLeftRadius: 28,
      borderBottomRightRadius: 28,
    },
    headerTopRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 10,
    },
    balanceLabel: {
      color: colors.headerMuted,
      fontSize: 18,
    },
    balanceValue: {
      color: colors.primaryContrast,
      fontSize: 34,
      fontWeight: "800",
      marginBottom: 24,
    },
    summaryRow: {
      flexDirection: "row",
      gap: 12,
    },
    summaryCard: {
      flex: 1,
      backgroundColor: colors.surface,
      borderRadius: 18,
      padding: 18,
    },
    summaryTitle: {
      fontSize: 16,
      color: colors.textSecondary,
      marginBottom: 12,
    },
    summaryValue: {
      fontSize: 18,
      fontWeight: "800",
      color: colors.textPrimary,
    },
    incomeText: {
      color: colors.income,
    },
    expenseText: {
      color: colors.expense,
    },
    content: {
      flex: 1,
      paddingHorizontal: 24,
      paddingTop: 20,
    },
    searchInput: {
      height: 52,
      backgroundColor: colors.surface,
      borderRadius: 16,
      paddingHorizontal: 16,
      fontSize: 15,
      color: colors.textPrimary,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 18,
    },
    typeFilterSection: {
      marginBottom: 18,
    },
    typeFilterRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    filterButtonSection: {
      marginBottom: 18,
      alignItems: "flex-start",
    },
    filterButton: {
      minHeight: 44,
      paddingHorizontal: 16,
      borderRadius: 999,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.primaryBorder,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
    },
    filterButtonActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    filterButtonText: {
      fontSize: 14,
      fontWeight: "800",
      color: colors.primary,
    },
    filterButtonTextActive: {
      color: colors.primaryContrast,
    },
    filterCountBadge: {
      minWidth: 22,
      height: 22,
      borderRadius: 999,
      backgroundColor: colors.surface,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 6,
    },
    filterCountText: {
      fontSize: 12,
      fontWeight: "800",
      color: colors.primary,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: colors.overlay,
      justifyContent: "flex-end",
    },
    filterModal: {
      backgroundColor: colors.background,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      paddingHorizontal: 24,
      paddingTop: 20,
      paddingBottom: 28,
    },
    filterModalHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 20,
    },
    filterModalTitle: {
      fontSize: 20,
      fontWeight: "800",
      color: colors.textPrimary,
    },
    filterModalCloseButton: {
      width: 40,
      height: 40,
      borderRadius: 999,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: "center",
      justifyContent: "center",
    },
    filterField: {
      marginBottom: 18,
    },
    filterLabel: {
      fontSize: 15,
      fontWeight: "800",
      color: colors.textSecondary,
      marginBottom: 10,
    },
    pickerWrapper: {
      backgroundColor: colors.surface,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.borderStrong,
      overflow: "hidden",
      justifyContent: "center",
      height: 52,
    },
    picker: {
      color: colors.textPrimary,
    },
    manageCategoriesButton: {
      minHeight: 44,
      borderRadius: 14,
      backgroundColor: colors.primaryMuted,
      borderWidth: 1,
      borderColor: colors.primaryBorder,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      marginBottom: 18,
    },
    manageCategoriesText: {
      color: colors.primary,
      fontSize: 14,
      fontWeight: "800",
    },
    dateFilterRow: {
      flexDirection: "row",
      gap: 12,
    },
    dateInput: {
      flex: 1,
      height: 52,
      backgroundColor: colors.surface,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.borderStrong,
      paddingHorizontal: 14,
      fontSize: 15,
      color: colors.textPrimary,
    },
    dateFilterError: {
      color: colors.danger,
      fontSize: 13,
      fontWeight: "600",
      marginTop: 10,
    },
    filterActions: {
      flexDirection: "row",
      gap: 12,
      marginTop: 4,
    },
    secondaryButton: {
      flex: 1,
      height: 52,
      borderRadius: 14,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.borderStrong,
      alignItems: "center",
      justifyContent: "center",
    },
    secondaryButtonText: {
      fontSize: 15,
      fontWeight: "800",
      color: colors.textMuted,
    },
    primaryButton: {
      flex: 1,
      height: 52,
      borderRadius: 14,
      backgroundColor: colors.primary,
      alignItems: "center",
      justifyContent: "center",
    },
    primaryButtonText: {
      fontSize: 15,
      fontWeight: "800",
      color: colors.primaryContrast,
    },
    sectionHeader: {
      marginBottom: 18,
      marginTop: 4,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "800",
      color: colors.textPrimary,
    },
    sectionCount: {
      fontSize: 15,
      color: colors.textMuted,
    },
    listContent: {
      paddingBottom: 100,
    },
    emptyState: {
      backgroundColor: colors.surface,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 20,
      alignItems: "center",
    },
    emptyStateTitle: {
      fontSize: 16,
      fontWeight: "700",
      color: colors.textPrimary,
      marginBottom: 8,
    },
    emptyStateText: {
      fontSize: 14,
      color: colors.textMuted,
      textAlign: "center",
      lineHeight: 20,
    },
    tabBarContainer: {
      position: "relative",
      backgroundColor: colors.surface,
    },
    addButton: {
      position: "absolute",
      alignSelf: "center",
      top: -24,
      width: 56,
      height: 56,
      borderRadius: 999,
      backgroundColor: colors.primary,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 4,
      borderColor: colors.surface,
      shadowColor: colors.shadowPrimary,
      shadowOffset: {
        width: 0,
        height: 6,
      },
      shadowOpacity: 0.28,
      shadowRadius: 10,
      elevation: 8,
    },
  });
}
